// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_ropasci
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-20, STEPS: `20`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `kalan-ThinkPad-T470s`, CPU: `Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_ropasci
// --extrinsic=*
// --steps=20
// --repeat=50
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallet-ropasci/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_ropasci.
pub trait WeightInfo {
	fn start_game() -> Weight;
	fn join_game() -> Weight;
	fn reveal_move(r: u32, ) -> Weight;
	fn on_initialize_betting(g: u32, ) -> Weight;
	fn on_initialize_revealing(g: u32, ) -> Weight;
}

/// Weights for pallet_ropasci using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Moves (r:0 w:1)
	fn start_game() -> Weight {
		(54_628_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn join_game() -> Weight {
		(58_212_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:1 w:1)
	/// The range of component `r` is `[1, 10000000]`.
	fn reveal_move(r: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 0
			.saturating_add((2_000 as Weight).saturating_mul(r as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci RevealingGamesIndex (r:2 w:2)
	/// The range of component `g` is `[1, 10000]`.
	fn on_initialize_betting(g: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 57_000
			.saturating_add((12_924_000 as Weight).saturating_mul(g as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(g as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(g as Weight)))
	}
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci RevealingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:2 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `g` is `[1, 10000]`.
	fn on_initialize_revealing(g: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 449_000
			.saturating_add((103_314_000 as Weight).saturating_mul(g as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((3 as Weight).saturating_mul(g as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((2 as Weight).saturating_mul(g as Weight)))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Moves (r:0 w:1)
	fn start_game() -> Weight {
		(54_628_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn join_game() -> Weight {
		(58_212_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:1 w:1)
	/// The range of component `r` is `[1, 10000000]`.
	fn reveal_move(r: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 0
			.saturating_add((2_000 as Weight).saturating_mul(r as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci RevealingGamesIndex (r:2 w:2)
	/// The range of component `g` is `[1, 10000]`.
	fn on_initialize_betting(g: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 57_000
			.saturating_add((12_924_000 as Weight).saturating_mul(g as Weight))
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(g as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(g as Weight)))
	}
	// Storage: RoPaSci BettingGamesIndex (r:1 w:1)
	// Storage: RoPaSci RevealingGamesIndex (r:1 w:1)
	// Storage: RoPaSci Games (r:1 w:1)
	// Storage: RoPaSci Moves (r:2 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `g` is `[1, 10000]`.
	fn on_initialize_revealing(g: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 449_000
			.saturating_add((103_314_000 as Weight).saturating_mul(g as Weight))
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(g as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((2 as Weight).saturating_mul(g as Weight)))
	}
}
